name: Test and Release

on:
  push:
    branches: '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml

    - name: Check Flutter version
      run: flutter --version

    - name: Run Flutter test
      run: |
        flutter pub get
        flutter test

    - name: Build android apk
      run: |
        flutter build apk

    - name: Get Release Note from Changelog
      run: |
        TAG_VERSION=0.1.0
        awk -v tag="$TAG_VERSION" '/^## /{p=0} $0 ~ "^## " tag{p=1} p' CHANGELOG.md > release_note.txt
        cat release_note.txt

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1.0
        release_name: Release v0.1.0
        body_path: release_note.txt

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: finance_management_v0.1.0.apk
        asset_content_type: application/zip

    - name: Clean up build files
      run: |
        rm -rf build
        echo "Cleaned up build files"
