name: Test and Release

on:
  push:
    branches: '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml

    - name: Check Flutter version
      run: flutter --version

    - name: Run Flutter test
      run: |
        flutter pub get
        flutter test

    - name: Build android apk
      run: |
        flutter pub get
        flutter build apk

    - name: Get git short sha
      id: get_sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: finance-management-${{ steps.get_sha.outputs.sha_short }}.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Clean up build files
      run: |
        rm -rf build
        echo "Cleaned up build files"
